### ISSUE TITLE
"ArrayBuffer.transfer" proposal is listed both in "Stage 0" and "inactive"

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/proposals#108]
Although not explicitly stated, it seems like there's an implicit distinction between *active* stage 0 proposals and *inactive* ones, where only active ones are in the "Stage 0" list.

The `ArrayBuffer.transfer` proposal seems to be a sole exception to this, however. Was this intentional, or just a mistake?

**Comment by ljharb** [comment]
The original proposal was withdrawn; @domenic has expressed interest in continuing it. I do not believe it has yet been presented to the committee in its second iteration.

In other words, it's intentional.
