### ISSUE TITLE
Compile proposal statistics at different stages

### ISSUE THREAD

**Issue by riwu** [tc39/proposals#122]
| Stage | Total proposals | Active proposals | Inactive proposals |
| - | - | - | - | 
| 0 | 125 | 11 | 22 |
| 1 | 125 | 11 | 22 |
| 2 | 125 | 11 | 22 |
| 3 | 125 | 11 | 22 |
| 4 | 125 | 11 | 22 |

Such summary statistics will be helpful to developers, eg. to decide whether to adopt a proposal at stage 0 by examining the failure rate of stage 0 proposals (in the above example, it will be 22/125 = 17%).

It can be further broken down into past 1-year, 3-year, lifetime statistics etc.

**Comment by riwu** [comment]
> The failure or success rate of proposals overall is entirely uncorrelated to the chances for success failure of any given proposal.

I think statistics do have some meaning...

Supposed only 10 out of 1000 stage 0 proposals moved to stage 1, I can conclude that in general, a stage 0 proposal has low probability of making it to stage 1.

On the other hand, if 999 out of 1000 stage 3 proposals moved to stage 4, I can conclude that any stage 3 proposal is very likely to get adopted.

**Comment by ljharb** [comment]
You can't, in fact, conclude that. Each proposal must be evaluated on a case-by-case basis.

**Comment by peter-mouland** [comment]
@riwu It's probably remembering what the stages mean as well - having developers 'adopt' a proposal before it is stage-4 and possibly stage-3 may do more harm than good as they wont be considered 'stable'.  

https://tc39.github.io/process-document/

**Comment by alangpierce** [comment]
I think there's a good point here, which is that people familiar with the process have some intuition on what the stages "really mean". For any given proposal, I'd bet that a TC39 member would have a reasonable guess at the probability that the proposal makes it into the language without significant change, the amount of time until it will reach stage 4, and the amount of time until it's available in browsers. Part of those estimates depend on the stage, although I'm sure the details of the proposal play a big role as well. I'm not sure that the official proposals repo or the process document is a good place to convey these types of estimates/intuition, though, and I agree that historical data might be misleading. But maybe there's a way (in addition to the process document) to make the system more understandable to newcomers. Maybe a blog post with a few case studies, for example.

@riwu FWIW, my general philosophy is that it's ok to use any feature supported by TypeScript, and TypeScript's philosophy is (mostly) that they wait until a proposal is stage 3 before implementing it. The TypeScript team has done the work of following the proposals closely and doing the risk analysis of adopting each feature early. But every unfinished proposal has risk, and if you want the lowest possible risk, you should only use stage 4 features. If you feel that you can accept more risk than TypeScript, then you may be able to find another open source project or company and go with their decisions.

**Comment by vcarl** [comment]
>I think there's a good point here, which is that people familiar with the process have some intuition on what the stages "really mean".

Maybe that's a reason to expand the process document or the readme to include a brief explanation of the level of effort associated with progressing to each state. I've been following the process for a few years now and have the impression that moving from 2 -> 3 is a significant hurdle, and that if somebody invests the effort to do so it indicates that the proposal is likely to continue progressing. 

I think the acceptance criteria and significance columns in the process document might be a little abstract for many developers. Many developers who have primarily been exposed to this process through Babel won't be as familiar with what's involved in writing a spec and what review process it goes through. Helping clarify what's difficult about advancing might help developers estimate for themselves.

**Comment by trotyl** [comment]
> For any given proposal, I'd bet that a TC39 member would have a reasonable guess at the probability that the proposal makes it into the language without significant change

@alangpierce For that reason the "success rate" won't help, a proposal could have been changed several times in same stage, and still breaking for users and implementers.

**Comment by littledan** [comment]
I think we should add more documentation about how the TC39 process works, but outside of the process document itself. It's hard to make changes to the process document, as some committee members worry that this would tie our hands in the future and make the committee less flexible (both in the direction of pushing proposals too fast and holding them back). We can have two separate things--the process document serving as our official rules, and a document with more context that describes how things have worked in the past and helpful, optional recommendations for champions and proposal reviewers.

**Comment by rajaraodv** [comment]
I am seeing stage-0 in production not realizing consequences. It also makes new developers learn lot more stuff/shi** than necessary and leaves them confused. In fact, something like this should be more prominently displayed on TC29's website.

**Comment by ljharb** [comment]
There are already separate efforts to improve documentation; however, i haven’t seen any compelling arguments that statistics will have any value on their own. Any objections to closing this?

**Comment by riwu** [comment]
I personally still find such statistics rather interesting to look at, but I will accept the consensus and let the matter rest.

Thanks all for your opinions/suggestions 👍
