### ISSUE TITLE
Required function parameters with `!`

### ISSUE THREAD

**Issue by Nektro** [tc39/proposals#123]
```js
function add(x, y) {
    // ... 
}
add();
```
The following code throws no error and assigns `undefined` to `x` and `y` in the body of the call. I am proposing using `!` on the right to show parameters that are required. This would also apply for `class` methods and constructors. And can be mixed with existing function declarations for allowing optional parameters that may or may not have default values

Example
```js
function fetch(url!, headers) {
    // ...
}
```

**Comment by alangpierce** [comment]
@Nektro This repository actually isn't the right place to suggest language features. You should post to the es-discuss mailing list instead. See the contributing docs for more information:
https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md
