### ISSUE TITLE
Native ZIP

### ISSUE THREAD

**Issue by catamphetamine** [tc39/proposals#130]
As applications are moving to the cloud more file formats require zipping and unzipping to conserve space (e.g. Excel).
There are a couple of Zip implementations but they are all a bit awkward ones. JSZip has bugs. zip.js is unsupported. Sometimes they hang on big archives, etc.
Not to mention they are about 100 KB in size (e.g. jszip.min.js).
Perhaps it would make sense for browsers to add native `Zip` class:
```js
const unzip = new Zip.Decompress()
unzip.on('entry', entry => ...)
file.createReadableStream().pipe(unzip)
```
```js
const zip = new Zip.Compress()
const file = File.initiateOutputStream('file.zip')
if (!file) return
zip.pipe(file)
zip.push('entry1', Blob|String)
zip.close()
```
Reopen if needed.

**Comment by xtuc** [comment]
Just for input, Java has a great [zip support](https://docs.oracle.com/javase/7/docs/api/java/util/zip/package-summary.html), including decoding in streaming.
