### ISSUE TITLE
What about adding new language features to enable writing DSL with Javascript

### ISSUE THREAD

**Issue by Albert-Gao** [tc39/proposals#137]
Love the capability in Kotlin which you can write your own DSL:

## Examples:

Things like generating model:

```kotlin
val people = People {
     name = "albert"
     job = {
          company = "NZ"
          title = "Dev"
    }
}
```

Or handling logic:

```kotlin
    permissionRequestHandler {
        actualRequestCode = requestCode
        expectRequestCode = this.requestCode
        
        onSuccess {
            // Do something when success
        }

        onFailure {
            // Do something for the failure case
        }

        onNeverAskAgain {
            
        }
    }
```

And you can do something like this:

```kotlin
html {
    body {
         div {
          }
    }
}
```

The best part is that these DSL are nothing more than plain Kotlin, it's just the syntax layer which makes it looks like a DSL. So you can actually add other normal Kotlin code into it. 

By doing this, it enables Domain Driven Design better in the language level. You can describe your core business logic in a hunman readable way. And even your marketing team can customize it. The only abstraction is the part that can be re-used across modules, but you can customize the other parts around it.

## Needed syntax support

It requires 2 features:

### 1. When the last parameter of a function is lambda, you can do this:

```kotlin
fun takeLambda( callback: () -> Unit ) {
     callback()
}

// Instead of calling it like this:
takeLambda ({
     // declare the lambda body
})

// you can do this
takeLambda {
    // put your lambda here
}

// Lambda can take parameter, when there is only one, its name will be `it`
takeLambda { it ->
    // put your lambda here
}

// even call it implictly
takeLambda {
   it.name = "ok"
}
```

### 2. Declare a receiver(Context) for the function

```kotlin
// We now enable the People context on this lambda
fun takeLambda( callback: People.() -> Unit ) {
     callback()
}

// Assume there is a People.name property, then you can do this
// Because the lambda got that context now
takeLambda {
      name = "albert"
}
```

Then you can write your own DSL.

This is pretty huge feature which will enable tons of great idea and cool new syntax to solve particular problem.

## A little bit more

To make it more declarative, there is another `infix` function concept in Kotlin.

```kotlin
// if we have a function like this:
infix fun People.add(s: String) { /* ... */ }
    
// Then we can do this:
AnyPeopleObject add "abc"
```

I previously used a mock library which uses these features to create some very good DSL to mock:

```kotlin
every {
     FuncCall()
} returns 2
```

Can we do this in Javascript ?

Sorry if I post in the wrong place.
Love Javascript and want it to evolve better.

**Comment by jasonwilliams** [comment]
Please read https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md before submitting requests

**Comment by Albert-Gao** [comment]
@jasonwilliams @littledan Thanks. Will read and try. Close it for now.

**Comment by Albert-Gao** [comment]
@littledan  Really thanks. I found that @samuelgoto already got a proposal for this: https://github.com/samuelgoto/proposal-block-params

Will see what I can do to contribute to it.
