### ISSUE TITLE
constructorof

### ISSUE THREAD

**Issue by tyxy96** [tc39/proposals#147]
I really down't know this submission proposal thing.

I have troubles with Monanding javascript and strategies choosing.

simple
if(symbol constructorof class) would save hours of work.

Thank you for implementation.

**Comment by tyxy96** [comment]
Also classes could be object, which have name property and "array" of decorators.

**Comment by IgnoredAmbience** [comment]
Are you looking for the `instanceof` operator? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by tyxy96** [comment]
No, I want to check if something is constructor of, not even being initialized...

Now I'm utilizing:
Symbol(o).toString().match(/class+\x20.\x20/).toString().split('\x20')[1]; to get class name.

**Comment by tyxy96** [comment]
sorry , === opretor worked, you can delete this.

**Comment by tyxy96** [comment]
actually "===" operator is working, sorry for bothering you.
