### ISSUE TITLE
A fresh look at date-time and timezone logic.

### ISSUE THREAD

**Issue by tracker1** [tc39/proposals#15]
Given the massive works that have been done to improve and enhance the language, it's time to give timezone and date-time logic an updated approach.  I'm not sure where to even start with this, but I was thinking it might be nice to get something similar to `moment.js` + `moment-timezone` inside JavaScript proper...  perhaps `Moment` to correspond to `Date` with a nod to the library.

I'm not suggesting it follow the moment library completely, but it might be a nice place to consider...  An alternative may be more additions to `Date` but I'm not sure that it's a good idea.   I'd also suggest that some minimal formats are accepted, and some behaviors established.

* Symbol constants for parts of time (`Moment.DAYS`, `Moment.MONTHS`, ...) in code, used for Date-time math... ex: `someMoment.add(5, Moment.DAYS)`
* Immutable by default, any method should return a new instance not mutate the underlying value.
* Timezone support, this is crucial, and I know it's *huge* to polyfill, so would be essential to getting browser vendors on board.
* `.toZone(timezoneId = localZone)` - instance from one timezone to another, with time adjustment
* `.asZone(timezoneId = localZone)` - instance zone changed to another, without time adjustment
*`.format(formatString)` - string formatting, including localization constructs/convensions
* parsing strings, ISO-8601 format must be used, or a specific format string must be specified, UTC is default unless a zone is specified as part of the string, can use toZone/asZone to make a local time instance.

Work with the moment.js team to create a new version as a polyfill that aligns with the proposed design, I know that there's been talk about going immutable in particular, and there's been a lot of good work there.

**Comment by ljharb** [comment]
Per this project's readme, see https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md for how to contribute to the language.
