### ISSUE TITLE
Built-in `deepCopy/deepClone` Prototype for both objects and iterable objects (based on the structured cloning algorithm)

### ISSUE THREAD

**Issue by IamManchanda** [tc39/proposals#150]
I have been working on a project where we had a serious serious need of deep copy.

The work out was this 
https://codepen.io/IamManchanda/pen/XYpVPY?editors=0012

<img width="1377" alt="screen shot 2018-07-13 at 12 22 25 pm" src="https://user-images.githubusercontent.com/4970624/42676892-7ee0d6c6-8697-11e8-9d8d-f0dac16ab8d7.png">

---

But here is the catch,
How I did it doesn't matter but what matters is that I have felt that everyone who is working on a complex app with frameworks like angular, vue and react would need such function 

---

Reason why I think so strongly that everyone in javascript community needs this is this 
=> https://gist.github.com/search?l=JavaScript&q=deepcopy
=> https://gist.github.com/search?l=JavaScript&q=deepclone
=> https://github.com/search?l=JavaScript&q=deepcopy&type=Repositories
=> https://github.com/search?l=JavaScript&q=deepclone&type=Repositories

---

And thus I decided to post this on lodash https://github.com/lodash/lodash/issues/3822
But here is what the author felt about it 

> Thanks for the suggestion. I'm happy to defer to user-land packages for this. My hope is that a built-in deep clone comes to browsers and Node (based on the structured cloning algorithm) then there would be no need for user-land implementations.

I think he is right ... I **personally** feel like a good way to do this would be to add a built-in **deepCopy Prototype for both objects and iterable objects**
That being said, if you guys think that good place would be [Global Built-in's](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) then that's great too

Anyways my case implementation could be like

```javascript
const harry = {
  name: 'Harry Manchanda',
  age: 25,
  social: [
    {
      website: 'twitter',
      username: '@harmanmanchanda',
    },
    {
      website: 'facebook',
      username: 'IamManchanda',
    },
  ],
};

// Object.prototype.deepCopy(), Array.prototype.deepCopy(), etc
const dev = harry.deepCopy();
dev.social[1].website = 'github'; 

console.log(harry);
console.log(dev);
```

which will output ...

<img width="904" alt="screen shot 2018-07-13 at 12 40 07 pm" src="https://user-images.githubusercontent.com/4970624/42677621-e942b58c-8699-11e8-9f42-10432c98368c.png">

**Comment by IamManchanda** [comment]
Hmmm... seems like this is not the right place to post this 
https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md

Seems like https://esdiscuss.org/ is the one but don't know how I can post there... not entirely accessible

**Comment by simonkberg** [comment]
The website is just an archive of the es-discuss@mozilla.org mailing list, so that's where you want to reach out.
https://mail.mozilla.org/listinfo/es-discuss

**Comment by errorx666** [comment]
Have you tried `JSON.parse( JSON.stringify( foo ) )`?  It will deeply clone non-recursive plain data objects, at least.

**Comment by ljharb** [comment]
See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md for how to suggest new ideas.

**Comment by shannon** [comment]
@IamManchanda I remembered seeing some discussion around similar functionality over at https://github.com/whatwg/html/pull/3414

Might be worth taking a look at that to see how your algorithm compares and how these features might overlap. Just FYI in case you are interested.

**Comment by IamManchanda** [comment]
Hey sorry guys ... I am interested ... Just didn't saw this ... Will look into this thread ahead this weekend ... Cheers!

**Comment by IamManchanda** [comment]
Hi Folks sorry for late response, 

I subscribed to the mailing list and then mailed it with same email address ... Hopefully this can proceed ahead now
