### ISSUE TITLE
Intl.MessageFormat proposal is missing from proposals list

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/proposals#153]
Intl.MessageFormat sometimes appears in agendas but is missing from ECMA402 proposals list. What stage is it?

**Comment by littledan** [comment]
This proposal isn't really championed right now. There's a lot to do outside of TC39 before it will be possible to make one. I think it's appropriate to say that it's not at a stage.

**Comment by ljharb** [comment]
Should it then be added to the "inactive" list?

**Comment by littledan** [comment]
There's just no proposal yet, AFAIK.

**Comment by ljharb** [comment]
aha, then in that case there's no action needed.
