### ISSUE TITLE
Remove rocket?

### ISSUE THREAD

**Issue by littledan** [tc39/proposals#161]
I'm not sure how useful the "rocket" column is. It doesn't seem to be very up-to-date. Generally, the agendas are a more frequently updated data source for what's proposed for advancement. Should we remove this column?

**Comment by ljharb** [comment]
Seems reasonable; I believe @rwaldron added it [here](https://github.com/tc39/ecma262/commit/1af3d1e7c24343e6c30bd60bd8b7b0c69ce8bd01#diff-04c6e90faac2675aa89e2176d2eec7d8). If there's no objections, we can certainly remove it.

**Comment by wmsbill** [comment]
As an outsider, I like to see the rocket, so that gives me a clue about the overall state of the proposals. As long as it stays up to date...

**Comment by Mouvedia** [comment]
It's particularly important for proposals with a lot of contentions, e.g. `#`.

**Comment by littledan** [comment]
It just hasn't been staying up to date. Is there a problem with looking at agendas to find what's going for stage promotion?

**Comment by ljharb** [comment]
If we decide to keep it, I can try to update it prior to each meeting, but it. does get tricky to do that without effort from proposal champions.

**Comment by Mouvedia** [comment]
@littledan at least you gotta link that agenda somewhere and not everyone has the time to read minutes.

**Comment by wmsbill** [comment]
> It just hasn't been staying up to date. Is there a problem with looking at agendas to find what's going for stage promotion?

Not at all. I just have to spend more time to gather that information. I only think that the rocket is more accessible to the general audience.

**Comment by ljharb** [comment]
@Mouvedia https://github.com/tc39/agendas

**Comment by littledan** [comment]
Note that, if we go with @ljharb 's plan in https://github.com/tc39/proposals/issues/161#issuecomment-434097811 , you'll have 10 days every two months with some more up-to-date information, and then back to just seeing what advanced for the rest of the cycle (with presumably no rockets posted).

**Comment by chicoxyzzy** [comment]
Most of rockets are outdated most of time and don't reflect current state of proposals so they are misleading more than helping

**Comment by Mouvedia** [comment]
Just make a stage checklist for champions that includes a bullet _PR on this repository_, case closed.

**Comment by chicoxyzzy** [comment]
Oh actually I misunderstood @Mouvedia 😄 Sorry, it's not really so good idea to force someone to do something not useful for proposal at all.

What I actually though is that we can add a column with links to issues like this https://github.com/tc39/proposal-global/issues/12. Not every proposal repo has this but at least we can add status issues to some of proposals

**Comment by littledan** [comment]
Could we tell people to check th upcoming agendas to learn about proposed advancement?

**Comment by lyleunderwood** [comment]
Agree with @littledan, fundamental issue seems to be that there's no direct route from proposals repo to agendas.

**Comment by ljharb** [comment]
I could certainly add a sentence and a link to the top of this repo pointing to the agendas.

**Comment by chicoxyzzy** [comment]
None of stage 0 proposals currently have a rocket. Maybe it's a good time to remove this column from that page? :)

**Comment by littledan** [comment]
@chicoxyzzy Sounds good, and it'd be great to see a PR removing it from the main proposals page as well, replacing it with links to the agendas and notes pages.

**Comment by ljharb** [comment]
They’re up to date now as of https://github.com/tc39/proposals/commit/340f63cd1d0d8df1554162591faa29a2bbeded8e , and i can easily take a pass at them after the January meeting advancement agenda deadline passes.

I’d like to hear from someone about the original motivations for the column, so we can know why the fence exists before tearing it down.

**Comment by littledan** [comment]
@ljharb I'd imagine up-to-date rockets would include a rocket for decorators, and the rocket removed for throw expressions. If we can direct people to the next meeting's agenda, people will be able to see the presentation links if the champion posted one there, and we'll save ourselves the work of keeping multiple pages with the same information in sync.
