### ISSUE TITLE
Problem: Can’t tell if proposals are actually finished, inactive, or what, just from looking at the proposals themselves

### ISSUE THREAD

**Issue by sideshowbarker** [tc39/proposals#162]
Concrete problem: Looking at https://github.com/tc39/proposal-trailing-function-commas, I can’t tell it’s in the “finished” state. Same for https://github.com/tc39/Array.prototype.includes. Etc.

I realize https://github.com/tc39/proposals/blob/master/finished-proposals.md can tell me — and https://github.com/tc39/proposals/blob/master/inactive-proposals.md for inactive ones — if I’m somebody who happens to already know to look there. But I’m sure many people don’t know that.

That risks causing confusion and wasting peoples’ time trying to figure out what the state is.

So it’d be helpful if something like this could happen:

* When https://github.com/tc39/proposals/blob/master/finished-proposals.md is updated to include a proposal that’s reached the “finished” state, the editor or somebody takes responsibility for adding text to the proposal document itself — in its own repo — to mark it as finished.

* When https://github.com/tc39/proposals/blob/master/inactive-proposals.md is updated to include a proposal that’s been put into the “inactive” state, the editor or somebody takes responsibility for adding text to the proposal document itself — in its own repo — to mark it as inactive.

It’d also be helpful of the group could consider adopting and documenting a policy that requires the above actions to happen.

**Comment by domfarolino** [comment]
Agreed this would be helpful

**Comment by ljharb** [comment]
Each proposals’ champion(s) are responsible for updating their own repo; indeed this repo is the source of truth.

Perhaps a consistent sentence at the top of every proposal pointing people to this repo for the stage would be helpful - i don’t think it’s something we can require at this time.

**Comment by ljharb** [comment]
Those sound like good ideas. Maybe a PR to add a section at the bottom of the readme (“guidelines for proposal champions”) and we can iterate there?

**Comment by littledan** [comment]
The source of truth for stage information is not any of these repositories, but what goes on in TC39. If the notes say something advanced, it has advanced, even if the repo is not updated. As a champion of more than one proposal, I try to keep things up to date, but I would definitely appreciate help here from people who notice issues.

Let's all collaborate on keeping this information up to date!

In addition to guidelines for champions, let's encourage PRs from everyone in the community for these sorts of updates--@chicoxyzzy and @anba have already been very helpful here, for example.

Many in TC39 can merge these PRs, if the champion is not available to do so and it's an obvious correctness fix. I don't know all the details of permissions, but at least I am able to merge them.

**Comment by xtuc** [comment]
This should be fixed by the future TC39 website. cc @codehag

**Comment by littledan** [comment]
@xtuc I don't see how; we will still have proposal repositories and other resources that need to be updated.

**Comment by xtuc** [comment]
Ideally implementation status would be fetched from various issue trackers and the status of the proposal form their GitHub repository.

More importantly, it will provide the single source of trouth which could avoid this question in the first place.

**Comment by littledan** [comment]
There will always be some level of manual updates, unless we parse the notes (which would be unreliable). Sometimes we agree to advance something and even forget to write it in the notes, but the people present all agree it happened. There will always be a level of human update here, and anyone can help out with that if they see an issue.

**Comment by littledan** [comment]
@ljharb OK, sounds good. We can encourage everyone to make PRs to update proposal repositories and this repository; normally, proposal champions will review and merge them, and in exceptional cases, the chair group will step in to help maintain proposals which are abandoned by their champions. How does that sound?

**Comment by ljharb** [comment]
Seems fine to me.

**Comment by ljharb** [comment]
Now that we have a "Last Presented" column, I think this can be closed. Happy to reopen if not.
