### ISSUE TITLE
Add controversial mark

### ISSUE THREAD

**Issue by rumkin** [tc39/proposals#179]
Add special mark (like 🚀) for controversial proposals, which need extra attention before been implemented, require more constructive discussion or should be delayed.

**Comment by ljharb** [comment]
That's generally something that you'd look at each proposal's repo to determine; it's pretty hard to make a general standard of "controversial", since by some metric, anything could be :-)

**Comment by rumkin** [comment]
I think good start point is proposals with probable breaking change like smoosh/flatten or globalThis.

**Comment by arcanis** [comment]
Maybe rather than a boolean it could be a metric such as the number of meetings during which the feature has been discussed? I guess "controversial" proposals have much more back-and-forth?

**Comment by ljharb** [comment]
The champion of a proposal would be the arbiter of such a mark on their own proposal here, too, so if they didn’t want it to show up, they’d be able to remove it. Are you implying that champions are acting in bad faith? I don’t think adding more noise to this table would address that problem (one I don’t agree exists).

**Comment by rumkin** [comment]
@ljharb 

> The champion of a proposal would be the arbiter of such a mark on their own proposal here, too, so if they didn’t want it to show up, they’d be able to remove it. .

Well, it's true while proposal is only a suggestion and has no stage level. Everything changes when it receive official status. JS is public property so there should be strict rules when and how to accept changes, when not, how to support discussion. Whole process should be transparent and open. Currently committee members are privileged. 

> Are you implying that champions are acting in bad faith?

No. I'm not about to blame someone. There is a human factor. Currently it looks like a train without stop-cock. I think there should be some clear process of how community can influence on the process. Situation with smoosh shown that there is some issues with that.

> I don’t think adding more noise to this table would address that problem (one I don’t agree exists).

This table isn't in it's perfect form. It's already a little bit noisy (Rocket issue #161) and could be optimized to be more informative. Static unchangeable information like author and champion names could be removed from it completely and moved to section with short proposal description.

@littledan 

Discussion of the private properties proposal is beyond the scope of this issue. It's just an example of such situation.

**Comment by rumkin** [comment]
> There are strict rules on all of those things - and committee members are privileged by necessity...

Privileges without limitations leads to misbalance and incorrect decisions. There is already exists such situations and I mentioned them before. 

> but this isn’t the place to discuss our process, either

Where is other public place to discuss it?

> It seems like what you’re really interested in is a change in our process, and not just altering the information displayed in this table.

I think that change of information could help to solve current problems without changing the process.

> I think it’s useful to have the static information here, and the specific information (including descriptions) on each proposal’s repo, where it can be most easily kept up to date.

Well as final solution I propose to add a link to public discussion to each proposal. And thumbs up/down could be an indicator of community relation.

**Comment by littledan** [comment]
You can find public discussion about each proposal in its issue tracker. Maybe we should document that fact more clearly somewhere.

**Comment by ljharb** [comment]
Each proposal in the table already links to the repo, which is where all public discussion about it can be had.

**Comment by rumkin** [comment]
@littledan @ljharb 

Thanks for your time. I see that this issue in current form is too general to have a solution to find support from members. But I'm sure there are many possibilities to enhance current information model to make process more efficient. So I will create new issue with more strict and clear proposals.
