### ISSUE TITLE
esdiscuss.org problem

### ISSUE THREAD

**Issue by CreatorVilius** [tc39/proposals#186]
Not sure if this is place to discuss about this.
In esdiscuss.org, it says to send message to specific email, when I posted, I haven't received any replies, or anything and I checked esdiscuss.org and my post doesn't exist there.

**Comment by ljharb** [comment]
You may need to check your spam folder?

**Comment by CreatorVilius** [comment]
I did. Nothing.

**Comment by ljharb** [comment]
Did you fill out the form here first? https://mail.mozilla.org/listinfo/es-discuss

**Comment by CreatorVilius** [comment]
Oh, nope. Sorry.

**Comment by ljharb** [comment]
You have to register an account before it can know who you are, and before it will accept your emails or send you any.

**Comment by CreatorVilius** [comment]
Oh, I am going to update status whenever it will work, or not.

**Comment by CreatorVilius** [comment]
Thank you. It works.
