### ISSUE TITLE
Where's the proposal for the Date.prototype.toString change in ES2018?

### ISSUE THREAD

**Issue by tjcrowder** [tc39/proposals#191]
`Date.prototype.toString` changed between [ES2017](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-todatestring) and [ES2018](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-todatestring), defining the format rather than leaving it as "implementation defined." Where's the proposal for that change? I don't see it listed on [the finished proposals list](https://github.com/tc39/proposals/blob/master/finished-proposals.md) (or the in-progress, etc.).

**Comment by ljharb** [comment]
It wasn’t a proposal; it was a needs-consensus PR - https://github.com/tc39/ecma262/pull/1252, i believe.

**Comment by ljharb** [comment]
In general, if every browser already does it, it's not significant - it's a spec bug (that the spec doesn't match reality). Seems like https://github.com/tc39/ecma262/pull/848 is actually where the change happened, and where most of the discussion occurred.

(in general, yes, you have to follow both every issue/PR on this repo as well as to ecma262 to keep fully up to date, but you can also review agendas every two months to see what "needs consensus" items were discussed).

**Comment by bakkot** [comment]
I do think the proposals repo should track needs-consensus / normative & non-bugfix PRs. The distinction between "needs-consensus PR" and "proposal" is useful for members of TC39, but not so much people just following JS's development.

**Comment by ljharb** [comment]
That’s certainly something we could track in another document, but you can also search the needs consensus label in ecma262 - maybe a link to that label search is sufficient?

**Comment by bakkot** [comment]
A link to the label would go a long way. I like tracking them in a document because you can watch the repository to get notified of changes, which is nice.

**Comment by ljharb** [comment]
Unfortunately watching only notifies for PRs, not for commits.

**Comment by bakkot** [comment]
Easy solution to that problem: protect master.

**Comment by ljharb** [comment]
@bakkot i've turned that on in the past, and gotten very strong pushback - there are folks who have insisted on retaining the ability to push directly.

**Comment by bakkot** [comment]
Which folks? Can we maybe talk to them again and see if there's some other way we can address their concerns?

**Comment by tjcrowder** [comment]
@ljharb - Looks like it was [this PR](https://github.com/tc39/ecma262/pull/848)? (Why am I asking? Just to make sure I'm navigating these things correctly. :-) ) TIA
