### ISSUE TITLE
Block params current status

### ISSUE THREAD

**Issue by macor161** [tc39/proposals#212]
Not an issue but is it possible to know the current status of the [block params](https://github.com/samuelgoto/proposal-block-params) proposal? It hasn’t been updated for over a year now and I received no answers from the person in charge (@samuelgoto) when I asked for more information.

Thanks

**Comment by ljharb** [comment]
https://github.com/samuelgoto/proposal-block-params/issues/35 is the right place to ask; as indicated [here](https://github.com/tc39/proposals/blob/master/stage-1-proposals.md) the proposal is stage 1 and was last presented on in [November 2017](https://github.com/tc39/tc39-notes/blob/be8c2af6d6dcfc9630e00ea15bbabf1a415245cb/es8/2017-11/nov-30.md#9iiia-block-params-to-stage-1).

Unfortunately, there’s really no new information to be had until the champion replies.

**Comment by macor161** [comment]
Thanks @ljharb for the quick response. Just another question (let me know if this is not the right place to ask) What happens if a proposal is abandoned by its champion? Is there a process in place to handle those kind of situations?

**Comment by allenwb** [comment]
Wow, what a failure of institutional memory!  This idea was extensively discussed during ES6 development as an alternative to arrow functions. Arrows won.  Kind of scary that this could have reached stage 1 without any mention or reference to that previous TC39  work:

https://web.archive.org/web/20110615161817/http://wiki.ecmascript.org/doku.php?id=strawman:block_lambda_revival 
https://web.archive.org/web/20111027022900/http://wiki.ecmascript.org/doku.php?id=strawman:paren_free
https://mail.mozilla.org/pipermail/es-discuss/2012-January/019520.html  (one of many message on several monumental ES-discuss threads 2011-2012)
https://mail.mozilla.org/pipermail/es-discuss/2012-March/021872.html  decision time
https://mail.mozilla.org/pipermail/es-discuss/2012-March/021879.html
https://mail.mozilla.org/pipermail/es-discuss/2012-March/021879.html why block lambdas were rejected:
> In general I sensed a new consensus: it's too late to wedge TCP into JS, 
at least under any "___ function syntax". Allen held out hope for 
block-lambdas later but others (Mark and I at least) view them as 
effectively ruled out by arrows.

**Comment by ljharb** [comment]
Stage 1 merely means we’re intending to discuss it further; certainly that sounds like a useful issue to file on the proposal itself.

**Comment by macor161** [comment]
@ljharb @allenwb Thanks to both of you for clearing this up. Very much appreciated. 
I will fill an issue on the proposal's page.

**Comment by littledan** [comment]
@allenwb Thanks for assembling those cross-references. We did discuss the arrow function history in TC39, but maybe the notes don't capture this well. I think this proposal is extremely unlikely to move forward for those reasons.
