### ISSUE TITLE
Generator arrow functions proposal repo

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/proposals#216]
Generator arrow functions proposal ([stage 1](https://github.com/tc39/tc39-notes/blob/master/meetings/2016-09/sept-29.md#arrow-generator-revisit)) doesn't have its own repository. Can I help with it? If someone will create a repo, I can add some basic information to it and try to write a spec draft.

**Comment by ljharb** [comment]
cc @domenic @brendaneich

(but i imagine if you create your own repo and set it up, we could transfer that in easily enough, and the champions would appreciate it)

**Comment by ORESoftware** [comment]
Looking at the link, as far as aesthetics

```js
let f = () => * {}
```

whoa. why not:

```js
let f = *() => {}
```

but with a single param it might get weird:

```js
let f = *a => {}
let f = *(a,b) => {}
```

**Comment by khaosdoctor** [comment]
> Looking at the link, as far as aesthetics
> 
> ```js
> let f = () => * {}
> ```
> 
> whoa. why not:
> 
> ```js
> let f = *() => {}
> ```
> 
> but with a single param it might get weird:
> 
> ```js
> let f = *a => {}
> let f = *(a,b) => {}
> ```

I actually think `*() => {}` or `*a => {}` looks better than the first one, or even `()* => {}` and `a* => {}` and `(a,b)* => {}` (just to match `function *`). It is, in my opinion, much more aesthetic and also follow the current `function*` guidelines.

**Comment by ljharb** [comment]
Let’s please save discussion of the proposal for its repo once it exists :-)

**Comment by benjamn** [comment]
You can mark this comment as off-topic too, but I don't want us to forget the possibility of introducing a new `=*>` token for this, since that would be totally unambiguous, and hasn't been mentioned elsewhere (as far as I can see).

**Comment by Simonwep** [comment]
This issue could also just transferred to the final repo (if it get's opened), so we can keep the comments.

And since the generator-function syntax got their star just after the keyboard
```js
function* name([param[, param[, ... param]]]) {
   statements 
}
```

i'd also vote for @ORESoftware 's `*() => {}`, wouldn't be that big of a change. And putting a star in the middle of the arrow looks a little bit confusing IMO :suspect:

**Comment by benjamn** [comment]
It seems risky/distracting to judge aesthetics without first limiting the pool of options to just the ones that have no parsing ambiguities. The last time TC39 discussed this proposal, almost every option was potentially ambiguous, so we need to tread extra carefully here, and not just rely on subjective feelings.

**Comment by chicoxyzzy** [comment]
Notes from previous discussions from September 2016 TC39 meeting
https://github.com/tc39/tc39-notes/blob/master/meetings/2016-09/sept-27.md#11ic-generator-arrow-functions
https://github.com/tc39/tc39-notes/blob/master/meetings/2016-09/sept-29.md#arrow-generator-revisit

This discussion is really important, though I agree with @ljharb, we need to move it to proposal repo. I'll post a link to it later.

**Comment by chicoxyzzy** [comment]
Repo: https://github.com/chicoxyzzy/proposal-generator-arrow-functions
Syntax discussion: https://github.com/chicoxyzzy/proposal-generator-arrow-functions/issues/2

I'm not sure that I can transfer this issue to my personal repo though.

**Comment by ljharb** [comment]
@chicoxyzzy once the proposal repo is in the tc39 org, we can transfer the issue.

**Comment by chicoxyzzy** [comment]
Is it possible to transfer separate messages? Otherwise I think that we can just close this issue in favor of chicoxyzzy/proposal-generator-arrow-functions#2

**Comment by ljharb** [comment]
No. This should be closed, since the repo's created, but I think we should still transfer the issue in the future.
