### ISSUE TITLE
Question: What does a finished proposal imply?

### ISSUE THREAD

**Issue by andykais** [tc39/proposals#218]
Hi! I'm just someone who wants to know a bit more about the process, and hopefully this will be useful if someone else stumbles on to this.

Could someone explain what a finished proposal implies? Taking dynamic imports for example (just moved to finished_proposals.md in #217), I believe an implementation has already landed in [most browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and [nodejs](https://nodejs.org/api/esm.html#esm_code_import_code_expressions) under the `--experimental-modules` flag. Were these implementations updated alongside this proposal document? Does this proposal being finished mean that there will be no more modifications to the spec in any of the implementations? Does it indicate that these features will be marked stable in nodejs soon?

**Comment by ljharb** [comment]
Finished means stage 4, and merged into the spec.

Shipping implementations begins happening in stage 3, before the proposal is finished.

For node, the ESM implementation is still in progress, so i wouldn’t expect dynamic import to be marked stable until the entire ESM implementation is.

The [process document](https://tc39.github.io/process-document/) may also be helpful.

**Comment by andykais** [comment]
Thank you! That is a clear explanation. This line from the process document is also helpful:
> When an addition is accepted at the “candidate” (stage 3) maturity level, the committee is signifying that it believes design work is complete and further refinement will require implementation experience, significant usage and external feedback.
