### ISSUE TITLE
Finish transfer of tc39-transfer/dynamic-code-brand-checks

### ISSUE THREAD

**Issue by mikesamuel** [tc39/proposals#227]
https://github.com/tc39-transfer/dynamic-code-brand-checks was [merged from two proposals](https://github.com/tc39-transfer/dynamic-code-brand-checks#historical-note) that were approved for stage 1 from stage 0 last meeting.  It's part of @tc39-transfer, but should be part of @tc39.

**Comment by mikesamuel** [comment]
Request to merge at https://docs.google.com/document/d/1r7AC6frhrRxqphqIbvYqClYqksAZLjDZeZPN5Kst1jY/edit#heading=h.v28wzrmf3z34

> AVK: My comment is would like to see this merged with prior proposal. Not clear how they interact and need both to do anything useful. Doesn’t seem you can have one or the other.

**Comment by ljharb** [comment]
@mikesamuel please don’t post links to notes docs; link to the tc39-notes repo only.

cc @tc39/chair-group for final transfers to the tc39 org.

**Comment by mikesamuel** [comment]
@lhjarb.  Sorry.  Will do.

**Comment by mikesamuel** [comment]
@tc39/chair-group Is there anything I need to do before this transfer can proceed?

**Comment by gesa** [comment]
I seem to have missed the ping for this. i'll take a look at my notification settings and transfer that repo
