### ISSUE TITLE
optional type declaration for function parameter and return value like Python

### ISSUE THREAD

**Issue by lithic** [tc39/proposals#239]

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for hw to best suggest new features for the language.

**Comment by lithic** [comment]
@ljharb is this one can be reopened?

**Comment by ljharb** [comment]
No, new feature suggestions don’t belong in this repo either.
