### ISSUE TITLE
Array.forEach should return promise

### ISSUE THREAD

**Issue by nitinbansal1989** [tc39/proposals#24]
I have a proposal as forEach function of array should return a promise of void. As the function is async, while coupling it with asynchronous "behavior" and yield is not working.

**Comment by djleonskennedy** [comment]
guess it'll never happens :)

**Comment by AndriiDidkivsky** [comment]
+1

**Comment by dallonf** [comment]
`Array.forEach` is async? That's news to me! Can you link to the source of that information?

It actually doesn't seem to be the case... running this snippet in the Chrome and Firefox consoles:
```
[1, 2, 3].forEach(i => console.log(i));
console.log(4);
```

logs "1, 2, 3, 4" as expected if `forEach` were synchronous.

**Comment by ljharb** [comment]
forEach is sync, and the web would break if it returned anything other than `undefined`, or else we'd probably make it `return this`.

Either way, this repo is not the place to make new proposals - the read me points you to https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md
