### ISSUE TITLE
TC39 new github theme is broken on mobile

### ISSUE THREAD

**Issue by c69** [tc39/proposals#254]
Is it possible to revert the custom theme, so issues in all proposals look and behave like default Github ?

**Comment by devsnek** [comment]
github doesn't have custom themes. whatever you're seeing is either your browser or github.

**Comment by wolfy1339** [comment]
GitHub recently updated it's mobile theme to look more like desktop

**Comment by ljharb** [comment]
This is not a question specific to any individual repo, since repos have no control over styling of github.com.

**Comment by c69** [comment]
my bad...

yesterday i was seeing those new styles only in TC39 repos (but not microsoft/typescript for example), today its on evert repo already... 

sorry for spam.
