### ISSUE TITLE
June meeting notes

### ISSUE THREAD

**Issue by piuccio** [tc39/proposals#292]
Any chance you could publish the June meeting notes on the repo?

On the README.md:

* `Intl.DurationFormat` says `June 2020` but the link points to the February notes.
* `Intl.Enumeration API` and `Smart Unit Preferences in Intl.NumberFormat` reached stage 1 in June 2020 but they're no link to the notes

**Comment by jridgewell** [comment]
There’s a 2 week delay after meeting for Review and editorial changes to the notes. We expect the June noes to be published in the 19th.

**Comment by chicoxyzzy** [comment]
Notes are published here https://github.com/tc39/notes/tree/master/meetings/2020-06

I'll update all June 2020 meeting links in this repo soon
