### ISSUE TITLE
Please move proposal-intl-enumeration and intl-displaynames-v2 from tc39-transfer into tc39

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposals#305]
Please transfer the repo

tc39-transfer/proposal-intl-enumeration
tc39-transfer/intl-displaynames-v2

to

tc39/proposal-intl-enumeration
tc39/intl-displaynames-v2

Both proposals advanced into Stage 1 tonight in TC39 Sept meeting

@LJHarb

**Comment by ljharb** [comment]
The chairs will have to do that :-) @robpalme @gesa @bterlson @MylesBorins

**Comment by FrankYFTang** [comment]
@ljharb  - notice I tag you because the document 
https://github.com/tc39/proposals#onboarding-existing-proposals
states
"if you are a TC39 delegate, but not a member of that organization, please contact @LJHarb"
So.. if that not the case, please change that page to avoid keep getting request.

**Comment by MylesBorins** [comment]
Both repos have been transferred with existing admin / write permissions in tact.

**Comment by ljharb** [comment]
@FrankYFTang that's talking about the tc39-transfer organization, which you are already a member of.
