### ISSUE TITLE
Move inactive proposal to `inactive-proposals.md`

### ISSUE THREAD

**Issue by septs** [tc39/proposals#313]
We are develop for [JSCIG](https://github.com/JSCIG) an official site, structured the all proposals data.

Some inactive proposals were found and have not been moved to `inactive-proposals.md`

https://github.com/JSCIG/dataset/blob/80679d9d491931c9f5d1b45b39b212da6ccead74/proposals.json#L3014-L3056

CC @ljharb

**Comment by ljharb** [comment]
What makes these inactive? Note that that document is specifically for rejected or withdrawn proposals, not simply ones that haven't had activity in awhile.
