### ISSUE TITLE
Uniform repo name style?

### ISSUE THREAD

**Issue by septs** [tc39/proposals#326]
https://github.com/tc39/proposals/pull/324/files
https://github.com/tc39/proposals/pull/325/files

CC @codehag @ljharb 

known but not renamed:
https://github.com/tc39/ecmascript_simd
https://github.com/tc39/ecmascript_sharedmem
https://github.com/tc39/dynamic-import-host-adjustment

**Comment by septs** [comment]
CC @littledan @lars-t-hansen @mikesamuel

**Comment by ljharb** [comment]
Generally speaking, we try to have proposal repos start with "proposal-", but I don't think it's necessarily worth the effort to enforce the convention.

**Comment by septs** [comment]
@ljharb

**Comment by codehag** [comment]
Thinking about this... It might be worth while, if we are doing a general update of all repos. Updating the names wouldn't be a burden when considering the cost of what we are planning anyway. I will keep this in mind and come back to it.

**Comment by ljharb** [comment]
@codehag ive offered to the chairs to audit all the existing proposal repos, eg to archive stage 4 proposals, and during that process, i plan to rename them all to start with “proposal-“ - but I’m still not sure it’s worth making it a requirement.

**Comment by mathiasbynens** [comment]
Keep in mind that repo tokens for CI integration might have to be reconfigured/recreated after a rename. Consider double-checking before renaming active repos.

(E.g. for my proposal repos, I tend to set up CI to automatically build and publish the HTML spec to `gh-pages`.)
