### ISSUE TITLE
BigInt Constructor does not conform to ALL other types.

### ISSUE THREAD

**Issue by lifeiscontent** [tc39/proposals#334]
when I call `Number()` I get `0`
when I call `String()` I get `""`
when I call `Array()` I get `[]`
when I call `Object()` I get `{}`
when I call `Boolean()` I get `false`
when I call `BigInt()` I get `Uncaught TypeError: Cannot convert undefined to a BigInt` this **SHOULD** return `0n`

**Comment by septs** [comment]
Original from https://es.discourse.group/t/567

**Comment by lifeiscontent** [comment]
@septs it seems no one is responding there. Is this the right place to be posting feedback like this?

**Comment by septs** [comment]
I don't know, the repo is tc39 proposals tracker

Not handle the problem

I think may need new proposal fix this "problem"
e.q: https://github.com/tc39/proposal-json-superset

**Comment by ljharb** [comment]
No, this isn’t the right place. The discourse is the right place.
