### ISSUE TITLE
add rbuckton/proposal-enum to stage-0-proposals.md

### ISSUE THREAD

**Issue by Mouvedia** [tc39/proposals#342]
https://github.com/rbuckton/proposal-enum is missing from https://github.com/tc39/proposals/blob/master/stage-0-proposals.md

**Comment by ljharb** [comment]
It’s not missing; it’s never been presented.

**Comment by matbgn** [comment]
@rbuckton any chance to present it formally once? Or due to architectural breaking changes there is no "near" chance to see i integrated?
