### ISSUE TITLE
Change name of branch from 'master' to 'main'

### ISSUE THREAD

**Issue by jesselpalmer** [tc39/proposals#346]
Would you consider changing the name of the `master` branch to `main`? GitHub has made this super easy to do: https://docs.github.com/en/github/administering-a-repository/renaming-a-branch. Thank you for your consideration!

**Comment by septs** [comment]
Why?

**Comment by ljharb** [comment]
Eventually we’ll change all our repos to main; i haven’t had a chance to do so here yet, but I’ll take care of it soonish.

**Comment by jesselpalmer** [comment]
@ljharb awesome!

**Comment by iugo** [comment]
> Why?

Political correctness, or anti-discrimination.

**Comment by moonrailgun** [comment]
Nowaday, PC is impact everywhere?
