### ISSUE TITLE
please add type hints to JavaScript just like  python,typescript is not good choise

### ISSUE THREAD

**Issue by 564064202** [tc39/proposals#382]
please add type hints to JavaScript just like  python,typescript is not good choise.

**Comment by devsnek** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

**Comment by 564064202** [comment]
@devsnek why close it?

**Comment by Jack-Works** [comment]
> Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

@564064202 We do not accept adding new features via a GitHub issue. Please make a formal proposal for it through the link above.

**Comment by theScottyJam** [comment]
Additionally, you may be interested in some of the existing discussions around this topic on the TC39 forms.

Here's one discussion I started: https://es.discourse.group/t/runtime-types-and-many-other-functional-ideas/1043
Another discussion on someone trying to make a minimal type system: https://es.discourse.group/t/type-fixing/918
A similar idea here: https://es.discourse.group/t/introducing-types-to-js-without-type-annotations/419
A proposal for a "use typed" directive: https://es.discourse.group/t/use-typed-directive/535
And an idea to allow typescript syntax, but have it be ignored: https://es.discourse.group/t/execute-typescript-directly/560
