### ISSUE TITLE
moving call-constructor proposal to its own repo

### ISSUE THREAD

**Issue by trusktr** [tc39/proposals#389]
@wycats @allenwb It would be nice to move the `call constructor()` proposal to its own `proposal-` repo, and move it along.

It can enable some interesting patterns, like function-less class-factory mixins. For example:

```js
const one = new One
const two = new Two

class OneTwo extends One(Two) {...}

const oneTwo = new OneTwo
```

where a `call constructor()` is used for the implementation of the `One(Two)` mixin application.

**Comment by ljharb** [comment]
Tha proposal was withdrawn, and has no current champion.

If a delegate wants to champion it further, then they certainly should make a new repo for it. The "workingdocs" in the ecma262 repo are there for legacy reasons and will likely be removed.
