### ISSUE TITLE
Splice Improvement

### ISSUE THREAD

**Issue by wffranco** [tc39/proposals#394]
Sorry if is not the right place but I have no time for all the process.

I propose to add a new way to call splice in arrays.

I will use an example. Suppose i have a constant with a list of products with prices, and i want to exclude some of then (maybe prices over 1000$).

If is a constant, I can't make a filter and overwrite it.
Currently the choice should be travel the array manually (we have different options: for/foreach/reduce), find the ids and remove them one by one.

My proposal is to improve the splice method, and allowing to use the `filter` format:
```
const products = [...];
const removed = products.splice(product => product.price > 1000);
// like in the normal splice, this could return the removed items
```
that way we can simplify the way to remove elements in an array (if we can't or we don't want to use filter for it)

**Comment by ljharb** [comment]
The process does take a lot of time, so if someone doesn't have time for it, there's not much that will happen.

https://github.com/tc39/proposals/blob/main/CONTRIBUTING.md → https://github.com/tc39/ecma262/blob/HEAD/CONTRIBUTING.md → https://github.com/tc39/ecma262/blob/HEAD/CONTRIBUTING.md#creating-a-new-proposal
> To make a feature request, document the problem and a sketch of the solution with others in the community, including TC39 members. One place to do this is the [TC39 Discourse](https://es.discourse.group/); another is the Matrix chat room).
>
> Your goal will be to convince others that your proposal is a useful addition to the language and recruit TC39 members to help turn your request into a proposal and shepherd it into the language. Once a proposal is introduced to the committee, new features are considered by the committee according to the TC39 process document.
>
> You can look at existing proposals for examples of how proposals are structured, and some delegates use this template when creating repositories for their proposals. Proposals need to have a repository and be moved to the TC39 org on GitHub once they reach Stage 1.

**Comment by wffranco** [comment]
mutate methods not always is a bad idea, if the functionality is similar.
string replace could receive string or regex in the first parameter.
normal `for` after years now allows `for ( in )` and `for ( of )`, originally only supported `for(a; b; c)` sintaxis.
so not always is a bad idea.

**Comment by hax** [comment]
@wffranco This is not the right place. For new ideas u could go here: https://es.discourse.group/
