### ISSUE TITLE
Idea: Sort the tables of proposals most-recently-discussed-first

### ISSUE THREAD

**Issue by brad4d** [tc39/proposals#396]
This is regarding the tables at https://github.com/tc39/proposals#readme

The proposals in the table are sorted by the date they advanced to that stage.
Since they're sorted oldest to newest, the stuff at the top of the table is often the least active.

It would be nice to have the most active stuff at the top by ordering the table with the most-recently-presented first.

**Comment by ljharb** [comment]
It's sorted by the date they advanced to that stage; other plenary presentations don't cause the order to change.

**Comment by tabatkins** [comment]
That said, reversing the ordering might still be worthwhile.

**Comment by brad4d** [comment]
@ljharb thanks for the correction.

**Comment by brad4d** [comment]
Wait, the title of the column does say "last presented".
Is that a mistake?

**Comment by brad4d** [comment]
Sorry. Nevermind. I just realized the sorting doesn't match that field.

**Comment by brad4d** [comment]
Fixed the OP.

**Comment by ljharb** [comment]
I suppose we could, but the proposals that need the most attention are the ones that are currently sorted at the top - the current order seems like the better one to me.

**Comment by brad4d** [comment]
I guess the best order all depends on what you want to find out when you look at the table.

**Comment by concavelenz** [comment]
@ljharb How much attention have you giving `function.sent`?

**Comment by ljharb** [comment]
@concavelenz i'm not sure what you're asking. I'm the one that last brought it up at plenary, in July 2019.
