### ISSUE TITLE
Optional chaining skip nested object next levels

### ISSUE THREAD

**Issue by laukstein** [tc39/proposals#398]
I wish optional chaining (?.) to have a better design.
`const obj = {a: {}}` currently needs `obj.a?.b?.c?.d?.()` in order not to fall into a code exception.

Instead, if **obj.a.b** doesn't exist, I propose `obj.a?.b.c.d()` to be enough - skip nested object next levels if found **obj.a.b** as not existing.

p.s. [tc39@proposal-optional-chaining](https://github.com/tc39/proposal-optional-chaining) archived read-only, that's the reason I'm propose it here.

**Comment by fisker** [comment]
```js
({a: {}}).a.b?.c.d()
```

**Comment by ljharb** [comment]
This repo isn’t the place to discuss this sort of thing; try the discourse: https://es.discourse.group/

**Comment by laukstein** [comment]
Open in https://es.discourse.group/t/optional-chaining-skip-nested-object-next-levels/1192
