### ISSUE TITLE
Typed Objects is not abandoned

### ISSUE THREAD

**Issue by iddan** [tc39/proposals#40]
https://github.com/tc39/ecma262/commit/02455e5e2964f62b13818c6fd23289381ecafdf8

**Comment by ljharb** [comment]
The [second comment](https://github.com/tc39/ecma262/commit/02455e5e2964f62b13818c6fd23289381ecafdf8#commitcomment-19555957) is still the case - that nothing new has been presented to the committee. When that happens, the proposal can be added to the list.
