### ISSUE TITLE
idea: import {aa,bb} as cc  from 'some-module'

### ISSUE THREAD

**Issue by chenbimo** [tc39/proposals#430]
import {aa,bb} as cc  from 'some-module'

when i call the aa or bb like this

cc.aa
cc.bb

**Comment by six-ponies** [comment]
您好，您的邮件已收到，我将尽快给您回复。谢谢

**Comment by bzk1994** [comment]
你好，来信已收到

**Comment by tinydogio-joshua** [comment]
I like this. 😀

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

**Comment by chenbimo** [comment]
> I like this. 😀

i do.
