### ISSUE TITLE
Unless/until.

### ISSUE THREAD

**Issue by arthurwolf** [tc39/proposals#433]
I'm not actually proposing the feature.

I'm asking whether this feature (unless(x) <=> if(!), like in Perl) has ever been proposed, and if so where was it proposed? I searched but couldn't find anything.

Thanks!

**Comment by ljharb** [comment]
The place to search for that is https://es.discourse.group (or https://esdiscuss.org for historical discussions). I don't believe it was ever an official proposal, but given that ASI exists and `unless` is already a valid identifier, I'd imagine it wouldn't be possible.
