### ISSUE TITLE
Please create Stage 1 float16 repo

### ISSUE THREAD

**Issue by petamoriken** [tc39/proposals#453]
@leobalter The W3C ColorWeb CG suggests adding `Float16Array` to ECMAScript, and prototyping it in browsers.

https://lists.w3.org/Archives/Public/public-colorweb/2022Dec/0014.html

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

**Comment by bakkot** [comment]
@ljharb Float16 is already a stage 1 proposal per https://github.com/tc39/proposals/blob/main/stage-1-proposals.md. This is a suggestion for adding a repository for it.

**Comment by ljharb** [comment]
oohhh thanks, i misunderstood.

**Comment by bakkot** [comment]
I have gone ahead and [made a repo for this](https://github.com/tc39-transfer/proposal-float16array), and written the (very small) spec text, so we have space to track it. I've linked ColorWeb CG's proposal in the motivation section.

The proposal itself is very little spec text, so if someone is able to bring it to committee in March and the committee is convinced of the use case I think it could advance quickly. If no one else is able to I would be willing to bring it myself, although I'm not very familiar with the space.
