### ISSUE TITLE
link of proposal-async-await is outdated

### ISSUE THREAD

**Issue by ayugioh2003** [tc39/proposals#457]
link of proposal-async-await is outdated
and status of this REPO is Public archived, can't create new issue or PR

REPO:
- https://github.com/tc39/proposal-async-await

old link is outdated
- https://tc39.github.io/ecmascript-asyncawait

maybe this link is correct
- https://tc39.es/proposal-async-await/

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/5466631/216270254-f6cf93d0-d61c-4eb0-93b3-a9ac5d3815f7.png">

**Comment by six-ponies** [comment]
您好，您的邮件已收到，我将尽快给您回复。谢谢
