### ISSUE TITLE
Move SIMD to inactive proposals?

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/proposals#46]
According to https://github.com/tc39/ecmascript_simd/commit/c6ca655dcbfc014d82f3ec500c2e41db34a1dee8, SIMD should be moved to inactive proposals.

**Comment by chicoxyzzy** [comment]
Alternatively it should move to stage 1 according to https://github.com/tc39/tc39-notes/blob/master/es8/2017-03/mar-21.md#conclusionresolution-10

**Comment by ljharb** [comment]
The resolution there is "stage will remain at stage 3"; I think it's best to leave things as-is for now.

**Comment by chicoxyzzy** [comment]
Fixed https://github.com/tc39/proposals/commit/35e0032d8b1cb5249a80629eabdd2c444acdea6a
