### ISSUE TITLE
Permissions for proposal-canonical-tz repo

### ISSUE THREAD

**Issue by justingrant** [tc39/proposals#470]
I'm one of the champions of [tc39/proposal-canonical-tz](https://github.com/tc39/proposal-canonical-tz), but it looks like I don't have the correct permissions for the repo. For example, I can't see the Settings tab. Could I get help to upgrade my permissions in this repo?

Also, my GH Pages deploy actions are failing (see https://github.com/tc39/agendas/pull/1371#issuecomment-1535793420), which may or may not be related to the permissions problem. But without access to the Settings tab I can't troubleshoot the problem. 😢

**Comment by bzk1994** [comment]
你好，来信已收到

**Comment by six-ponies** [comment]
您好，您的邮件已收到，我将尽快给您回复。谢谢

**Comment by mathiasbynens** [comment]
@tc39/chairs

**Comment by ljharb** [comment]
Permissions fixed; I’ll debug the action with you offline.
