### ISSUE TITLE
Data Structures and Algorithms

### ISSUE THREAD

**Issue by Stebinraj** [tc39/proposals#494]
Manually we don't need to implement Data Structures and Algorithms. This feature consume time of a developer and making use of Node JS more popular and user friendly.

**Comment by Aschen** [comment]
This explain a lot
<img width="325" alt="image" src="https://github.com/tc39/proposals/assets/4447392/6b9c2ae4-a7aa-4b40-b5fe-fd1f753d1c5b">

**Comment by Najada** [comment]
@Aschen not very nice

**Comment by robpalme** [comment]
@Aschen TC39 has a [Code of Conduct.](https://tc39.es/code-of-conduct/).  Please familiarize yourself with it - we're all aiming to be respectful and friendly here.

**Comment by zloirock** [comment]
@robpalme I don't think that closing this issue without explaining that it's not the correct place for this follows this code of conduct.

**Comment by geromegrignon** [comment]
Besides the link in the header of the issue page towards the contribution guide, here is the first line of the issue template:

> This repository is NOT the right place to suggest new ECMAScript features.

**Comment by zloirock** [comment]
The author of the post might have missed this. It's hard to write this as a comment to

![image](https://github.com/tc39/proposals/assets/2213682/8082ae04-83de-417c-8bc3-55a3c3bc45a1)

instead of silent closing as "not planned"?
