### ISSUE TITLE
Object field name shorthand

### ISSUE THREAD

**Issue by Nokel81** [tc39/proposals#54]
Allow `.`s to be included in object field names so that you can short hand field names.

Examples:
```javascript
var obj = {
    field1: "val",
    field2.field3: "val2"
};
```
becomes
```javascript
var obj = {
    field1: "val",
    field2: {
        field3: "val2"
   }
};
```
```javascript
var obj = {
    field1: "val",
    field2.field3: "val2",
    field2.field4: "val3"
};
```
would equal
```javascript
var obj = {
    field1: "val",
    field2: {
        field3: "val2",
        field4: "val3"
   }
};
```
and even
```javascript
var obj.field = "val";
```
becomes
```javascript
var obj = {
    field: "val"
};
```

**Comment by hzoo** [comment]
Thanks for the issue!

You can follow https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md to make a proposal - it isn't just making an issue in this particular repo.

**Comment by Nokel81** [comment]
Okay, I will then and when I am done I will close this issue
