### ISSUE TITLE
Listing RegExp.escape

### ISSUE THREAD

**Issue by slikts** [tc39/proposals#6]
It could be worthwhile to list the [RegExp.escape](https://github.com/benjamingr/RegExp.escape) proposal with the inactive ones to make it more discoverable; it's still relevant and there's agreement about how to proceed with it, just no one's done the work.

**Comment by ljharb** [comment]
@slikts it's solidly an inactive proposal, as `RegExp.escape` as proposed was sadly firmly rejected. A separate proposal for a tagged template literal function is being worked on, but would be considered a separate proposal.

I'll add `RegExp.escape` to the list of inactive proposals, however.
