### ISSUE TITLE
Clarify Stage 0 proposals requirements

### ISSUE THREAD

**Issue by Ginden** [tc39/proposals#71]
I'm not sure where this issue should be, but:
* [tc39/proposals/stage-0-proposals.md](https://github.com/tc39/proposals/blob/ea9a898/stage-0-proposals.md) claims that champion is required for stage 0 proposal
  * [Stage 0 proposals] are "planned to be presented to the committee by a TC39 champion"
  * All stage 0 proposals have TC39 champions 
* [tc39/proposals/README.md](https://github.com/tc39/proposals/blob/aef81631df132636384b6165b248e1389dbd9bf3/README.md) links to tc39/process-document as authoritative
* [tc39/process-document/index.html](https://github.com/tc39/process-document/blob/3942d2b074b0c25afbdbb78e096114151578a13c/index.html) claims that champion is required for stage 1 proposal.
  * Champion must be identified to advance to stage 1
  * No champion is required for stage 0
* [tc39/ecma262](https://github.com/tc39/ecma262/blob/f0f337bb9403e06397e8616c92f794cbf987de10/CONTRIBUTING.md) agrees with `tc39/proposals/stage-0-proposals.md`.

Some of these documents should be fixed, and I'm not sure which ones.

**Comment by ljharb** [comment]
I'd say it's the process document. The committee has been very clear that non-members can not bring any proposal without a member sponsoring it. Note, however, that's not necessarily the same as a champion.

In other words, stage 0 does not require a champion, but it still requires a TC39 member's cooperation.

**Comment by ljharb** [comment]
Closing in favor of https://github.com/tc39/process-document/issues/11
