### ISSUE TITLE
Broken link to proposal Relationships on Stage 0

### ISSUE THREAD

**Issue by Alexsey** [tc39/proposals#75]
At [Stage 0 proposals page](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md) link that is provided for Relationships - http://wiki.ecmascript.org/doku.php?id=strawman:relationships - can't be loaded

**Comment by ljharb** [comment]
ping @dherman, wiki's down again

For now, https://web.archive.org/web/20160804042554/http://wiki.ecmascript.org/doku.php?id=strawman:relationships works (always good to check archive.org)

I'll leave this issue open before making any changes, in case the wiki gets fixed sooner than later.

**Comment by GrosSacASac** [comment]
Defensible Classes link broken it seems

**Comment by js-choi** [comment]
See also tc39/ecma262#1090.

**Comment by littledan** [comment]
I'd suggest that things which only have an Internet Archive link be classified as "inactive".

**Comment by ljharb** [comment]
That’s up to their champions; I’ll ask them at the next meeting.
