### ISSUE TITLE
Some updates from september missing from the README tables

### ISSUE THREAD

**Issue by afmenez** [tc39/proposals#82]
The [notes from september](https://github.com/tc39/tc39-notes/blob/master/es8/2017-09/summary.md) seem to make some changes that are not reflected on the [README tables](https://github.com/tc39/proposals/blob/master/README.md) yet:
- `Atomics.waitAsync` to Stage 2
- `Intl.RelativeTimeFormat` to Stage 3

**Comment by littledan** [comment]
Thanks for filing this issue. Unfortunately, RelativeTimeFormat didn't actually reach Stage 3; there was an error in note-taking. I have made a PR against the notes to correct this.

**Comment by afmenez** [comment]
OK, and what about `Atomics.waitAsync`?

**Comment by littledan** [comment]
cc @syg

**Comment by lars-t-hansen** [comment]
Shu assured me it reached stage 2 so I sure hope that's correct :)

**Comment by afmenez** [comment]
So the notes are correct, but the [README](https://github.com/tc39/proposals/blob/master/README.md) is still wrong for `Atomics.waitAsync`.  Isn't this the same proposal as `Atomics.waitNonblocking` there?

**Comment by keithamus** [comment]
Sorry for the note-taking errors! 🙇

**Comment by ljharb** [comment]
If I missed updating something in the readme, a PR to update it, referencing links to the notes, would be very helpful. Thanks!

**Comment by syg** [comment]
> Isn't this the same proposal as Atomics.waitNonblocking there?

It is, it got renamed because everyone disliked the `waitNonBlocking` name.
