### ISSUE TITLE
Proposal: sugar syntax for structuring

### ISSUE THREAD

**Issue by streamich** [tc39/proposals#85]
I often see objects created like this:

```js
const obj = {
  isMuted: state.volume.isMuted
};
```

this proposal is to allow this equivalent syntax instead:

```js
const obj = {
  state.volume.isMuted
};
```

The last key `isMuted` of the `state.volume.isMuted` expression will be set as a key on the new object.

**Comment by ljharb** [comment]
Please see https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md; this isn't the place to post new proposals.

Separately, https://github.com/rbuckton/proposal-shorthand-improvements might be the proposal you're looking for.
