### ISSUE TITLE
Distinguish authors from champions

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposals#93]
Can we please add an “author” column and distinguish authors from champions?

Context: I’m championing multiple proposals from community members. I don’t want credit for *writing* these proposals, though. It feels wrong to conflate being a champion with authorship.

Despite me explicitly mentioning the proposal authors during each of my presentations, some committee members mistakenly thought _I_ was the author.

I’ve seen similar confusion in articles and blog posts about proposals, where a champion was credited as an author, based on the table in this repository.

**Comment by mathiasbynens** [comment]
cc @gibson042 @RReverser

**Comment by ljharb** [comment]
The column does already say "champions", which isn't supposed to imply "author".

The concern I have here is that the majority case has the author and the champion being the same; which would mean that in that case, either there'd be redundant info, or a bunch of blank columns.

Maybe an alternative is using a ✏️ emoji to indicate authorship (with a legend at the top), or - to avoid flooding the list with emojis, only non-author champions could get a 🎈 or 🏆 emoji?

**Comment by mathiasbynens** [comment]
I’m fine with using emoji over adding an extra column, although it might complicate programmatically getting the list of proposals (e.g. https://prop-tc39.now.sh/ by @bevacqua).

**Comment by mathiasbynens** [comment]
> The column does already say "champions", which isn't supposed to imply "author".

You and I know that, but apparently there is still confusion, and if we can clarify that easily I think we should.

Note that the champions column currently contains some authors that are non-champions. As such, the amount of redundancy could be more minimal than we might think.

**Comment by ljharb** [comment]
Any preference of emoji choice?

**Comment by mathiasbynens** [comment]
I like your suggestions. On top of 🏆 for champion, @rauschma suggested ✍️ for author (instead of ✏️). I don’t really care, although I would prefer adding a column.

**Comment by rauschma** [comment]
What if someone is both author and champion? I’m OK with the table only listing champions as long as the proposals list the authors at the beginning of their readme. At the moment, there is no definitive way (AFAICT) to look up authors.

**Comment by mathiasbynens** [comment]
There has been pushback to adding more requirements for proposals, so I doubt that will happen. (E.g. I recently [suggested](https://github.com/tc39/process-document/issues/10) that proposals should mention implementation status in their `README`, and people didn’t seem to like it.)

Having two columns would be the clearest, IMHO. I’ll get a PR ready so we can see what that would look like.
